# -*- coding: utf-8 -*-
"""White Noise Generator with LFO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjRIw4dDrJRewt1h3PrHy-up7mOoDPCZ
"""

# HowTo use:
# Click the "Run all" button in the top tab
# Watch the code compile and generate playable white noise, and white noise with an LFO!

# Scroll down to find the audio generated.
# Play wih the constants defined at the top of each block.

# Thanks for checking it out
# - Geoff Bremner

# More from me here: https://linktr.ee/gbaudio

# UNCOMMENT IN COLAB print("Creating Cloud Environment... Please wait a moment...")

# UNCOMMENT IN COLAB !pip install numpy==2.0 scipy==1.14.0 --force-reinstall > /dev/null

# RAIN LFO CONFIG (NEW: LFO for subtle volume pulsing)
RAIN_LFO_FREQ = 1  # 0.2 Hz means a full volume cycle every 5 seconds
RAIN_LFO_DEPTH = 0.63 # Max volume swing (0.0 = none, 1.0 = silence)

import numpy as np
from scipy import signal as sig
from scipy.io.wavfile import write
from IPython.display import Audio

# Constants
SAMPLE_RATE = 48000  # Standard audio sample rate
DURATION = 10        # 10 seconds of sound
T = DURATION * SAMPLE_RATE

# 1. Generate White Noise (random values between -1 and 1)
white_noise = np.random.uniform(-1, 1, T).astype(np.float32)

nyquist = 0.5 * SAMPLE_RATE # Calculate Nyquist frequency once

def normalize_audio(audio_array: np.ndarray) -> np.ndarray:
    """
    Normalizes an audio array to a peak amplitude of 1.0 (0 dBFS).

    Args:
        audio_array: A numpy array representing the audio signal.

    Returns:
        The normalized numpy audio array.
    """
    # Find the maximum absolute value (peak) in the array
    peak_amplitude = np.max(np.abs(audio_array))

    # Check for silent audio to avoid division by zero
    if peak_amplitude == 0:
        print("Warning: Attempted to normalize a silent track.")
        return audio_array

    # Divide the entire array by the peak amplitude
    normalized_array = audio_array / peak_amplitude

    return normalized_array

# Rain Filter Setup
f_cutoff_rain = 2000 # Cutoff frequency: 2000 Hz
order_rain = 5       # Filter order

# Design the filter coefficients
normalized_cutoff_rain = f_cutoff_rain / nyquist
b_rain, a_rain = sig.butter(order_rain, normalized_cutoff_rain, btype='low', analog=False)

# Apply the filter to the White Noise
rain_sound = sig.lfilter(b_rain, a_rain, white_noise)

# Mix (if you had other components, you would sum them here)
final_mix = rain_sound

# Normalize the final result using the function
final_audio_normalized = normalize_audio(final_mix)

print("White noise sound component.")

# Playback
Audio(final_audio_normalized, rate=SAMPLE_RATE)

# MODIFY ABOVE LFO PARAMS TO CHANGE LFO!
# Thanks for stopping by!
# - Geoff Bremner


# --- APPLY LFO MODULATION FOR RAIN VOLUME ---
# Generate time vector
t = np.linspace(0., DURATION, T, endpoint=False)

# Generate LFO sine wave (ranges from 0 to 1)
raw_lfo = 0.5 * (np.sin(2 * np.pi * RAIN_LFO_FREQ * t) + 1.0)

# Scale LFO for modulation (e.g., if DEPTH=0.4, signal ranges from 0.6 to 1.0)
# This prevents the sound from going completely silent.
modulation_signal = (1.0 - RAIN_LFO_DEPTH) + (raw_lfo * RAIN_LFO_DEPTH)

# Apply modulation
rain_sound *= modulation_signal
# -------------------------------------------

# Mix (if you had other components, you would sum them here)
final_mix = rain_sound

# Normalize the final result using the function
final_audio_normalized = normalize_audio(final_mix)

print("White noise sound component (with LFO) generated.")

Audio(final_audio_normalized, rate=SAMPLE_RATE)